Friendshipsv1
defoebrand/ror-social-scaffold pull request #3
Opened 2020-09-21 15:37 UTC by m15e

- [ ] Created a model with associations and requested features for friendships

- [ ] Created tests

2020-09-21 17:59 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @defoebrand  and @m15e ! 👋 
 You have also done a wonderful job with your project so far! 🤩 🎖️ It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The User's timeline should only show posts from the logged in users and their friends. 
screenshot of the requirements 👇 
![Screen Shot 2020-09-21 at 7 54 16 PM](https://user-images.githubusercontent.com/48804258/93802808-3bd4d100-fc44-11ea-9d59-f603c2c1b4ab.png)
screenshot from your webpage 👇 
![Screen Shot 2020-09-21 at 7 54 44 PM](https://user-images.githubusercontent.com/48804258/93802865-4becb080-fc44-11ea-8eaa-c18e5bb4d2bb.png)
![Screen Shot 2020-09-21 at 7 54 54 PM](https://user-images.githubusercontent.com/48804258/93802883-527b2800-fc44-11ea-8b73-8c6f1420c5c0.png)
   - As you can see, the user is not friends with Brittany but her post appears on the timeline. 
****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-09-21 17:59 UTC, BrittanyBlake commented on app/models/user.rb
> +  # scope :not_user_friends, -> { where('user_id != ?', current_user.id) }
- [ ] Please remove commented code. It is bad practice to leave it in.

2020-09-22 14:04 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Mark Rode & Defoe Defoe** 
Great job following the improvements of the last review :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [x] After creating a post it should immediately available in "timeline" and "stay in touch".
- [x] After I reject a friendship request I should be able to request friendship to that same user.
- [ ] After my friendship request is rejected I should be able to request a friendship again to that same user.
- [ ] include tests for negative scenarios, you might use "to_not eql" and "to_not be_an".

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-09-22 14:35 UTC, defoebrand commented
All reviewer requests have been implemented except the last one. The model tests currently in place include numerous to eq false, which is the same as saying to not eql true. Unless there is a need for specifically calling out 'to not eql' then we have already implemented many negative test scenarios.

2020-09-22 18:05 UTC, uche-inyama approved these changes
## Approved

### Hi team :wave: 

Go ahead with the next milestone.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-09-23 06:55 UTC, merged